### PR TITLE
Committing and updating

### PR DESCRIPTION
**Pull request by spamidig**
merge branch to master

### CODE REVIEW

**Comment by spamidig** [comment]
accept branch

**Comment by nsfphyman** [comment]
I would not merge until I give you a go ahead.  I am playing around and it seems silly to do too much.

**Comment by spamidig** [comment]
Do you want to test the branch code before merging. We can go back to an older version in the master as well, if needed.

Thanks,
Sudhakar.

**Comment by nsfphyman** [comment]
I have not yet a sufficient number of changes to test it yet.  I just put in some new files and edited a file.  I will let you know.

**Pull request merged**
